name: Run Python Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Single stable version (3.13 isn't fully supported yet)

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest -v  # Verbose mode shows which tests pass/fail